#!/usr/bin/env node
/* Rebuilds assets/photos/manifest.json from whatever image files are in
 * assets/photos/. Run after dropping in photographs:  node tools/photos.js  */
const fs = require("fs"), path = require("path");
const root = path.join(__dirname, "..");
const dir = path.join(root, "assets", "photos");
const people = require(path.join(root, "data", "people.js")).people;
const known = new Set(people.map(p => p.slug));

const files = fs.readdirSync(dir).filter(f => /\.(jpe?g|png|webp)$/i.test(f));
const exts = new Set(files.map(f => path.extname(f).slice(1).toLowerCase()));
if (exts.size > 1) {
  console.error("Mixed extensions found: " + [...exts].join(", ") +
    ". The page loads one extension for everyone — pick one and set it below.");
}
const slugs = [], unknown = [];
for (const f of files) {
  const slug = path.basename(f, path.extname(f));
  (known.has(slug) ? slugs : unknown).push(slug);
}
slugs.sort();

fs.writeFileSync(path.join(dir, "manifest.json"), JSON.stringify({
  _comment: "Generated by tools/photos.js. Slugs listed here have an image file in this directory; anything else falls back to the monogram in assets/avatars/.",
  ext: exts.size ? [...exts][0] : "jpg",
  photos: slugs
}, null, 2) + "\n");

console.log(`manifest.json: ${slugs.length} photo(s) of ${people.length} people.`);
if (unknown.length) console.warn("Ignored (no matching slug in data/people.js): " + unknown.join(", "));
const missing = people.filter(p => !slugs.includes(p.slug)).map(p => p.slug);
if (missing.length) console.log(`Still using monograms (${missing.length}): ` + missing.join(", "));
